# Generated by Django 3.1.7 on 2021-03-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_auto_20210319_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
